version = 0.1

[default.deploy.parameters]
stack_name = "identity-governance-dev"
resolve_s3 = true
s3_prefix = "identity-governance-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "Stage=dev"
disable_rollback = false
tags = "Project=IdentityGovernance Environment=dev"
